# Modeling

In [3]:
# Libraries to load
# !pip install lightgbm

In [4]:
from datetime import datetime
start_time = datetime.now()

# Libraries to load
# !pip install lightgbm

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
import lightgbm as lgb
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
%matplotlib inline

print('LOAD DURATION: ', datetime.now() - start_time) # load time about 30 seconds

LOAD DURATION:  0:00:09.794864

In [3]:
# import pickle

In [5]:
fileNames = ['vars_age_entities','vars_velocity_days_since_relative_velocity','vars_count_entities_1_a','vars_count_entities_1_b','vars_count_entities_1_c','vars_count_entities_2','vars_count_entities_3_a','vars_count_entities_3_b']

In [6]:
vars_keep = pd.read_excel("VarsFS.xlsx")

In [7]:
# vars_keep # homephone_count_3, fulladdress_homephone_count_30

In [8]:
filterCols = list(vars_keep['variable name']) #+ ['homephone_count_3', 'fulladdress_homephone_count_30']

In [9]:
len(filterCols)

30

In [10]:
filterCols

['fulladdress_count_30',
 'ssn_dob_count_30',
 'fulladdress_unique_count_for_dob_homephone_60',
 'address_count_30',
 'fulladdress_count_0_by_3',
 'fulladdress_unique_count_for_name_dob_30',
 'fulladdress_unique_count_for_ssn_name_dob_60',
 'fulladdress_unique_count_for_name_dob_60',
 'fulladdress_unique_count_for_ssn_name_dob_30',
 'fulladdress_unique_count_for_fulladdress_dob_60',
 'fulladdress_unique_count_for_fulladdress_dob_30',
 'ssn_name_dob_count_30',
 'name_dob_count_14',
 'name_dob_count_30',
 'fulladdress_unique_count_for_name_dob_7',
 'fulladdress_unique_count_for_dob_homephone_7',
 'fulladdress_unique_count_for_ssn_fulladdress_7',
 'fulladdress_unique_count_for_fulladdress_dob_7',
 'fulladdress_unique_count_for_ssn_name_30',
 'fulladdress_unique_count_for_ssn_name_7',
 'fulladdress_unique_count_for_ssn_7',
 'ssn_count_30',
 'fulladdress_unique_count_for_ssn_zip5_60',
 'fulladdress_unique_count_for_ssn_name_60',
 'fulladdress_count_3',
 'fulladdress_unique_count_for_ssn_lastname_7',
 'fulladdress_unique_count_for_ssn_name_3',
 'fulladdress_unique_count_for_ssn_lastname_3',
 'ssn_lastname_count_30',
 'fulladdress_unique_count_for_ssn_name_dob_7']

In [11]:
x = ['fulladdress_count_30',

'ssn_firstname_count_30',

'address_count_30',

'homephone_count_3',

'ssn_dob_count_30',

'fulladdress_homephone_count_30',

'ssn_dob_day_since',

'fulladdress_homephone_day_since',

'fulladdress_unique_count_for_ssn_name_app_age_60']
x

['fulladdress_count_30',
 'ssn_firstname_count_30',
 'address_count_30',
 'homephone_count_3',
 'ssn_dob_count_30',
 'fulladdress_homephone_count_30',
 'ssn_dob_day_since',
 'fulladdress_homephone_day_since',
 'fulladdress_unique_count_for_ssn_name_app_age_60']

In [12]:
x2 = ['fulladdress_count_30','ssn_dob_count_30','homephone_count_3','fulladdress_unique_count_for_dob_homephone_60','name_dob_count_30','fulladdress_unique_count_for_ssn_name_dob_60','address_count_30','fulladdress_unique_count_for_fulladdress_dob_60','fulladdress_unique_count_for_ssn_zip5_60','fulladdress_unique_count_for_fulladdress_dob_30','fulladdress_unique_count_for_name_dob_60','fulladdress_unique_count_for_name_dob_30','ssn_count_30']

In [13]:
x3 = ['fulladdress_count_30','ssn_count_30','homephone_count_3','fulladdress_unique_count_for_dob_homephone_60','fulladdress_unique_count_for_ssn_30','fulladdress_unique_count_for_name_dob_30','ssn_dob_count_30','fulladdress_unique_count_for_dob_homephone_30','ssn_name_count_0_by_30','fulladdress_unique_count_for_ssn_zip5_30','fulladdress_unique_count_for_ssn_name_dob_30','ssn_firstname_count_0_by_30','address_count_30','ssn_dob_count_14','ssn_firstname_count_30','name_dob_count_0_by_30','ssn_lastname_count_0_by_14','ssn_firstname_count_14','fulladdress_unique_count_for_ssn_name_dob_60','fulladdress_unique_count_for_ssn_zip5_60','fulladdress_unique_count_for_ssn_fulladdress_60','ssn_dob_count_0_by_30','ssn_name_dob_count_7','ssn_lastname_count_7','fulladdress_unique_count_for_name_dob_60','ssn_lastname_count_0_by_30','ssn_lastname_count_30','fulladdress_unique_count_for_fulladdress_dob_30','fulladdress_unique_count_for_name_fulladdress_60','ssn_count_0_by_14']

In [14]:
# filterCols = list(set(list(vars_keep['variable name']) + ['homephone_count_3', 'fulladdress_homephone_count_30'] + x2))
filterCols = x3.copy()
dfList = []
for i in fileNames:
    df = pd.read_pickle("D:\\Fraud Assignment 6 pickles backup\\Final\\"+str(i))
    if i == 'vars_age_entities':
        df = df.filter(filterCols + ['record','fraud_label'])
    else:
        df = df.filter(filterCols)
    dfList.append(df)
    del df
df = pd.concat(dfList,axis = 1)

In [15]:
len(df.columns)

32

In [16]:
df.columns

Index(['record', 'fraud_label', 'fulladdress_count_30', 'ssn_count_30',
       'homephone_count_3', 'ssn_dob_count_30', 'ssn_name_count_0_by_30',
       'ssn_firstname_count_0_by_30', 'address_count_30', 'ssn_dob_count_14',
       'ssn_firstname_count_30', 'name_dob_count_0_by_30',
       'ssn_lastname_count_0_by_14', 'ssn_firstname_count_14',
       'ssn_dob_count_0_by_30', 'ssn_name_dob_count_7', 'ssn_lastname_count_7',
       'ssn_lastname_count_0_by_30', 'ssn_lastname_count_30',
       'ssn_count_0_by_14', 'fulladdress_unique_count_for_dob_homephone_60',
       'fulladdress_unique_count_for_ssn_30',
       'fulladdress_unique_count_for_name_dob_30',
       'fulladdress_unique_count_for_dob_homephone_30',
       'fulladdress_unique_count_for_ssn_zip5_30',
       'fulladdress_unique_count_for_ssn_name_dob_30',
       'fulladdress_unique_count_for_ssn_name_dob_60',
       'fulladdress_unique_count_for_ssn_zip5_60',
       'fulladdress_unique_count_for_ssn_fulladdress_60',
       'fulladdress_unique_count_for_name_dob_60',
       'fulladdress_unique_count_for_fulladdress_dob_30',
       'fulladdress_unique_count_for_name_fulladdress_60'],
      dtype='object')

In [19]:
len(set(x3).intersection(set(df.columns)))

30

In [20]:
df.to_pickle("vars")

In [21]:
df = pd.read_pickle("vars")

In [22]:
df.head()

,record,fraud_label,fulladdress_count_30,ssn_count_30,homephone_count_3,ssn_dob_count_30,ssn_name_count_0_by_30,ssn_firstname_count_0_by_30,address_count_30,ssn_dob_count_14,...,fulladdress_unique_count_for_name_dob_30,fulladdress_unique_count_for_dob_homephone_30,fulladdress_unique_count_for_ssn_zip5_30,fulladdress_unique_count_for_ssn_name_dob_30,fulladdress_unique_count_for_ssn_name_dob_60,fulladdress_unique_count_for_ssn_zip5_60,fulladdress_unique_count_for_ssn_fulladdress_60,fulladdress_unique_count_for_name_dob_60,fulladdress_unique_count_for_fulladdress_dob_30,fulladdress_unique_count_for_name_fulladdress_60
0,1,0,1,1,1,1,30.0,30.0,1,1,...,1,1,1,1,1,1,1,1,1,1
1,2,1,1,1,1,1,30.0,30.0,1,1,...,1,1,1,1,1,1,1,1,1,1
2,3,0,1,1,1,1,30.0,30.0,1,1,...,1,1,1,1,1,1,1,1,1,1
3,4,0,1,1,1,1,30.0,30.0,1,1,...,1,1,1,1,1,1,1,1,1,1
4,5,0,1,1,1,1,30.0,30.0,1,1,...,1,1,1,1,1,1,1,1,1,1

In [18]:
# with open("D:\\Fraud Assignment 6 pickles backup\\Y_var.pkl",'rb') as fileName:
#     Y = pickle.load(fileName)

In [19]:
# X = pd.read_pickle("D:\\Fraud Assignment 6 pickles backup\\X_vars")

In [20]:
# print(len(Y))
# print(len(X))

In [23]:
# n = 15
# vars = df.filter(['record','fraud_label']+filterCols[0:n])#df.copy()
# vars['Fraud'] = Y
vars = df.copy()

In [24]:
len(vars.columns)

32

In [25]:
vars['fraud_label'].value_counts()

0    985607
1     14393
Name: fraud_label, dtype: int64

In [25]:
# %%time
# vars = pd.read_csv('vars_final_save.csv')

In [26]:
# use this to cap variables. For some problems it helps
Clip = 10

In [27]:
vars['fraud_label'].sum()

14393

In [28]:
vars.head(10)

,record,fraud_label,fulladdress_count_30,ssn_count_30,homephone_count_3,ssn_dob_count_30,ssn_name_count_0_by_30,ssn_firstname_count_0_by_30,address_count_30,ssn_dob_count_14,...,fulladdress_unique_count_for_name_dob_30,fulladdress_unique_count_for_dob_homephone_30,fulladdress_unique_count_for_ssn_zip5_30,fulladdress_unique_count_for_ssn_name_dob_30,fulladdress_unique_count_for_ssn_name_dob_60,fulladdress_unique_count_for_ssn_zip5_60,fulladdress_unique_count_for_ssn_fulladdress_60,fulladdress_unique_count_for_name_dob_60,fulladdress_unique_count_for_fulladdress_dob_30,fulladdress_unique_count_for_name_fulladdress_60
0,1,0,1,1,1,1,30.0,30.0,1,1,...,1,1,1,1,1,1,1,1,1,1
1,2,1,1,1,1,1,30.0,30.0,1,1,...,1,1,1,1,1,1,1,1,1,1
2,3,0,1,1,1,1,30.0,30.0,1,1,...,1,1,1,1,1,1,1,1,1,1
3,4,0,1,1,1,1,30.0,30.0,1,1,...,1,1,1,1,1,1,1,1,1,1
4,5,0,1,1,1,1,30.0,30.0,1,1,...,1,1,1,1,1,1,1,1,1,1
5,6,0,1,1,1,1,30.0,30.0,1,1,...,1,1,1,1,1,1,1,1,1,1
6,7,0,1,1,1,1,30.0,30.0,1,1,...,1,1,1,1,1,1,1,1,1,1
7,8,0,1,1,1,1,30.0,30.0,1,1,...,1,1,1,1,1,1,1,1,1,1
8,9,0,1,1,1,1,30.0,30.0,1,1,...,1,1,1,1,1,1,1,1,1,1
9,10,0,1,1,1,1,30.0,30.0,1,1,...,1,1,1,1,1,1,1,1,1,1

In [29]:
vars.shape

(1000000, 32)

In [30]:
vars.describe()

,record,fraud_label,fulladdress_count_30,ssn_count_30,homephone_count_3,ssn_dob_count_30,ssn_name_count_0_by_30,ssn_firstname_count_0_by_30,address_count_30,ssn_dob_count_14,...,fulladdress_unique_count_for_name_dob_30,fulladdress_unique_count_for_dob_homephone_30,fulladdress_unique_count_for_ssn_zip5_30,fulladdress_unique_count_for_ssn_name_dob_30,fulladdress_unique_count_for_ssn_name_dob_60,fulladdress_unique_count_for_ssn_zip5_60,fulladdress_unique_count_for_ssn_fulladdress_60,fulladdress_unique_count_for_name_dob_60,fulladdress_unique_count_for_fulladdress_dob_30,fulladdress_unique_count_for_name_fulladdress_60
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.00000,...,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,500000.500000,0.014393,1.064624,1.050823,1.449296,1.046097,29.547011,29.545271,1.078171,1.03226,...,1.038716,1.039362,1.036240,1.038982,1.043802,1.038559,1.038559,1.043294,1.038569,1.037934
std,288675.278933,0.119104,0.633831,0.513331,0.861622,0.496315,2.647104,2.651908,0.664121,0.47155,...,0.609942,0.610443,0.608032,0.610242,0.618063,0.613686,0.613686,0.617028,0.609549,0.612499
min,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.363636,1.363636,1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,250000.750000,0.000000,1.000000,1.000000,1.000000,1.000000,30.000000,30.000000,1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,500000.500000,0.000000,1.000000,1.000000,1.000000,1.000000,30.000000,30.000000,1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,750000.250000,0.000000,1.000000,1.000000,2.000000,1.000000,30.000000,30.000000,1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,1000000.000000,1.000000,30.000000,34.000000,32.000000,34.000000,30.000000,30.000000,30.000000,34.00000,...,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000

In [31]:
record_save = vars['record']
Y_save = pd.DataFrame(vars.loc[:,'fraud_label'])
Y_save.head()

   fraud_label
0            0
1            1
2            0
3            0
4            0

In [32]:
record_save

0               1
1               2
2               3
3               4
4               5
           ...
999995     999996
999996     999997
999997     999998
999998     999999
999999    1000000
Name: record, Length: 1000000, dtype: int64

## Scale and truncate field values

In [37]:
vars['fulladdress_count_30'].value_counts()

1     966530
2      28049
3       1416
4        493
5        434
6        393
7        371
8        343
9        319
10       282
11       253
12       214
13       183
14       153
15       120
16        94
17        78
18        59
19        51
20        45
21        35
22        24
23        19
24        13
25        10
26         7
27         4
28         3
29         3
30         2
Name: fulladdress_count_30, dtype: int64

In [33]:
X_no_scaling = vars.drop(columns = ['record','fraud_label'])
X_no_scaling.describe()

,fulladdress_count_30,ssn_count_30,homephone_count_3,ssn_dob_count_30,ssn_name_count_0_by_30,ssn_firstname_count_0_by_30,address_count_30,ssn_dob_count_14,ssn_firstname_count_30,name_dob_count_0_by_30,...,fulladdress_unique_count_for_name_dob_30,fulladdress_unique_count_for_dob_homephone_30,fulladdress_unique_count_for_ssn_zip5_30,fulladdress_unique_count_for_ssn_name_dob_30,fulladdress_unique_count_for_ssn_name_dob_60,fulladdress_unique_count_for_ssn_zip5_60,fulladdress_unique_count_for_ssn_fulladdress_60,fulladdress_unique_count_for_name_dob_60,fulladdress_unique_count_for_fulladdress_dob_30,fulladdress_unique_count_for_name_fulladdress_60
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.00000,1000000.000000,1000000.000000,...,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,1.064624,1.050823,1.449296,1.046097,29.547011,29.545271,1.078171,1.03226,1.048903,29.584207,...,1.038716,1.039362,1.036240,1.038982,1.043802,1.038559,1.038559,1.043294,1.038569,1.037934
std,0.633831,0.513331,0.861622,0.496315,2.647104,2.651908,0.664121,0.47155,0.499029,2.546141,...,0.609942,0.610443,0.608032,0.610242,0.618063,0.613686,0.613686,0.617028,0.609549,0.612499
min,1.000000,1.000000,1.000000,1.000000,1.363636,1.363636,1.000000,1.00000,1.000000,1.363636,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1.000000,1.000000,1.000000,1.000000,30.000000,30.000000,1.000000,1.00000,1.000000,30.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,1.000000,1.000000,1.000000,1.000000,30.000000,30.000000,1.000000,1.00000,1.000000,30.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,1.000000,1.000000,2.000000,1.000000,30.000000,30.000000,1.000000,1.00000,1.000000,30.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,30.000000,34.000000,32.000000,34.000000,30.000000,30.000000,30.000000,34.00000,34.000000,30.000000,...,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000

In [34]:
X = (X_no_scaling - X_no_scaling.mean()) / X_no_scaling.std()

In [35]:
# push in any outlier values
cols = X.columns
X.loc[:,cols] = X[cols].clip(upper=Clip)
X.loc[:,cols] = X[cols].clip(lower=-1*Clip)
# X = (X_no_scaling - X_no_scaling.mean()) / X_no_scaling.std()
X.describe()

,fulladdress_count_30,ssn_count_30,homephone_count_3,ssn_dob_count_30,ssn_name_count_0_by_30,ssn_firstname_count_0_by_30,address_count_30,ssn_dob_count_14,ssn_firstname_count_30,name_dob_count_0_by_30,...,fulladdress_unique_count_for_name_dob_30,fulladdress_unique_count_for_dob_homephone_30,fulladdress_unique_count_for_ssn_zip5_30,fulladdress_unique_count_for_ssn_name_dob_30,fulladdress_unique_count_for_ssn_name_dob_60,fulladdress_unique_count_for_ssn_zip5_60,fulladdress_unique_count_for_ssn_fulladdress_60,fulladdress_unique_count_for_name_dob_60,fulladdress_unique_count_for_fulladdress_dob_30,fulladdress_unique_count_for_name_fulladdress_60
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,...,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,-0.018176,-0.017667,-0.005814,-0.017649,0.000040,0.000036,-0.016786,-0.018502,-0.017457,0.000159,...,-0.019734,-0.019696,-0.019877,-0.019712,-0.019413,-0.019736,-0.019736,-0.019447,-0.019746,-0.019776
std,0.631721,0.587739,0.910935,0.571302,0.999597,0.999634,0.678129,0.519100,0.579481,0.998362,...,0.577521,0.578869,0.572323,0.578313,0.590648,0.579228,0.579228,0.588890,0.577309,0.577105
min,-0.101958,-0.099006,-0.521454,-0.092879,-10.000000,-10.000000,-0.117706,-0.068413,-0.097996,-10.000000,...,-0.063475,-0.064481,-0.059602,-0.063880,-0.070870,-0.062832,-0.062832,-0.070165,-0.063275,-0.061933
25%,-0.101958,-0.099006,-0.521454,-0.092879,0.171126,0.171472,-0.117706,-0.068413,-0.097996,0.163303,...,-0.063475,-0.064481,-0.059602,-0.063880,-0.070870,-0.062832,-0.062832,-0.070165,-0.063275,-0.061933
50%,-0.101958,-0.099006,-0.521454,-0.092879,0.171126,0.171472,-0.117706,-0.068413,-0.097996,0.163303,...,-0.063475,-0.064481,-0.059602,-0.063880,-0.070870,-0.062832,-0.062832,-0.070165,-0.063275,-0.061933
75%,-0.101958,-0.099006,0.639148,-0.092879,0.171126,0.171472,-0.117706,-0.068413,-0.097996,0.163303,...,-0.063475,-0.064481,-0.059602,-0.063880,-0.070870,-0.062832,-0.062832,-0.070165,-0.063275,-0.061933
max,10.000000,10.000000,10.000000,10.000000,0.171126,0.171472,10.000000,10.000000,10.000000,0.163303,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [36]:
# # separate data into modeling (traintest) and out of time
# X_trntst = X[0:833507]
# Y_trntst = Y_save[0:833507]
# X_oot = X[833507:]
# Y_oot = Y_save[833507:]

In [38]:
niter = 0
nitermax = 3
FDR3 = pd.DataFrame(np.zeros((nitermax,3)), columns=('trn', 'tst', 'oot'))
pd.options.mode.chained_assignment = None  # default='warn'

In [39]:
type(Y_save)

pandas.core.frame.DataFrame

### Model Function

In [40]:
def modelAndOutput(modelName, criterionDict, X, Y_save, filterCols,nitermax):
    """
    Function to fit a model on train, apply on test and calculate average FDR over number of iterations specified by nitermax
    
    Args:
    modelName(str): name of the model 
    criterionDict(dict): hyperparameter dict
    X(dataframe): containing input variables
    Y_save(dataframe): contains Y variable
    filterCols(list): list of columns that are ranked according to their importance (used to decide which variables for the model have to be used)
    nitermax(int): number of iterations to run for each model
    """
    countScenarios = len(criterionDict['n_variables'])
    FDR_results = []
    for i in range(0,countScenarios):
        X_trntst = X[0:833507]
        Y_trntst = Y_save[0:833507]
        X_oot = X[833507:]
        Y_oot = Y_save[833507:]
        n = criterionDict['n_variables'][i]
        X_trntst = X_trntst.filter(filterCols[0:n])
        X_oot = X_oot.filter(filterCols[0:n])
        X_oot_orig = X_oot.copy()
        
        FDR3 = pd.DataFrame(np.zeros((nitermax,3)), columns=('trn', 'tst', 'oot'))
        
        for niter in range(nitermax):  
            print("train-test-split")
            X_trn, X_tst, Y_trn, Y_tst = train_test_split(X_trntst, Y_trntst, test_size = .3)
            
            
            if modelName == 'DecisionTreeClassifier':
                model = DecisionTreeClassifier(criterion = criterionDict['criterion'][i], max_depth = criterionDict['max_depth'][i],
                                          max_features = criterionDict['max_features'][i], min_samples_split = criterionDict['min_samples_split'][i],\
                                                  min_samples_leaf = criterionDict['min_samples_leaf'][i])
                    
                    
                
            elif modelName == 'RandomForestClassifier':
                model = RandomForestClassifier(criterion = criterionDict['criterion'][i], max_depth = criterionDict['max_depth'][i],
                                          max_features = criterionDict['max_features'][i],min_samples_split = criterionDict['min_samples_split'][i],\
                                                  min_samples_leaf = criterionDict['min_samples_leaf'][i])

                
            elif modelName == 'lgb':
                model = lgb.LGBMClassifier(learning_rate = criterionDict['learning_rate'][i],\
                                               boosting_type = criterionDict['boosting_type'][i],\
                                               num_leaves = criterionDict['num_leaves'][i])
            
            elif modelName == 'LogisticRegression':
                if len([i for i in criterionDict.keys() if i!='n_variables'])!=0:
                    raise Exception("Hyperparameter tuning not implemented for Logistic Regression")
                model = LogisticRegression()

            elif modelName == 'MLPClassifier':
                model = MLPClassifier(hidden_layer_sizes = criterionDict['hidden_layer_sizes'][i],
                                          activation = criterionDict['activation'][i],
                                          solver = criterionDict['solver'][i],
                                          alpha = criterionDict['alpha'][i],
                                          learning_rate = criterionDict['learning_rate'][i],
                                          learning_rate_init = criterionDict['learning_rate_init'][i])
            
            elif modelName == 'SVC':
                model = SVC(kernel = criterionDict['kernel'][i],probability = True)
            
            elif modelName == 'KNeighborsClassifier':
                model = KNeighborsClassifier(n_neighbors = criterionDict['n_neighbors'][i],weights = criterionDict['weights'][i])

            else:
                raise Exception("Not implemented yet")
                
            
            print("model object created")
            
            X_oot = X_oot_orig.copy()
            X_trn_save = X_trn.copy()
            Y_trn_save = Y_trn.copy()

            print("training started")
            model.fit(X_trn, Y_trn.values.ravel())   
            print("training ended")
            predictions = model.predict_proba(X_trn_save)[:,1]
            X_trn['predicted'] = predictions
            X_trn['fraud_label'] = Y_trn_save['fraud_label']
            topRows = int(round(X_trn.shape[0]*0.03))
            temp = X_trn.sort_values('predicted',ascending=False).head(topRows)
            needed = temp.loc[:,'fraud_label']
            FDR3.loc[niter, 'trn'] = sum(needed)/sum(X_trn.loc[:,'fraud_label'])

            predictions = model.predict_proba(X_tst)[:,1]
            X_tst['predicted']=predictions
            X_tst['fraud_label'] = Y_tst['fraud_label']
            topRows = int(round(X_tst.shape[0]*0.03))
            temp = X_tst.sort_values('predicted',ascending=False).head(topRows)
            needed = temp.loc[:,'fraud_label']
            FDR3.loc[niter, 'tst'] = sum(needed)/sum(X_tst.loc[:,'fraud_label'])

            predictions = model.predict_proba(X_oot)[:,1]
            X_oot['predicted']=predictions
            X_oot['fraud_label'] = Y_oot['fraud_label']
            topRows = int(round(X_oot.shape[0]*0.03))
            temp = X_oot.sort_values('predicted',ascending=False).head(topRows)
            needed = temp.loc[:,'fraud_label']
            FDR3.loc[niter, 'oot'] = sum(needed)/sum(X_oot.loc[:,'fraud_label'])
            print(niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot'])
        print("Scenario "+ str(i))
        print(FDR3.mean())
        FDR_results.append(FDR3.mean())
        print(f"*************************Scenario {i} completed***********************************************") 

    resultDf = pd.DataFrame(criterionDict).join(pd.concat(FDR_results,axis = 1).T)
    resultDf
    resultDf['Best OOT'] = np.where(resultDf['oot'] == max(resultDf['oot']),1,0)
    resultDf['model'] = modelName 
    return resultDf

In [41]:
modelsToRun = ['LogisticRegression','DecisionTreeClassifier','RandomForestClassifier','lgb','MLPClassifier']#SVC
outputDfList = []

In [42]:
hpDict = {'DecisionTreeClassifier': {'n_variables':[5,15,15,15,15,30,5,30],
                                    'criterion':['gini','gini','entropy','gini','entropy','entropy','gini','gini'],
                                    'max_depth':[None,None,None,4,1000,2,None,10000],
                                    'min_samples_split':[2,2,2,2,2,2,100,2],
                                    'max_features':[5,15,15,15,15,10,5,30],
                                    'min_samples_leaf':[1,1,1,1,1,1,50,1]},
          
         'LogisticRegression': {'n_variables':[5,10,15,20,30]},
          
          'RandomForestClassifier': {'n_variables':[5,15,15,15,15,30,3,30,5,5,5],
                                    'criterion':['gini','gini','entropy','gini','entropy','entropy','gini','gini','gini','entropy','entropy'],
                                    'max_depth': [None,None,None,20,20,None,None,100,None,5,1000],
                                    'min_samples_split':[2,2,2,2,2,2,2,2,100,2,2], 
                                    'max_features':[5,15,15,15,15,10,3,30,5,5,5],
                                    'min_samples_leaf':[1,1,1,1,1,1,1,1,50,1,1]},
          
         'lgb': {'n_variables':[5,15,15,15,15,30,5,5],
                 'num_leaves' : [31,31,31,31,40,40,5,10000],
                 'learning_rate':[0.1,0.1,0.01,0.1,0.1,0.01,0.001,0.001],
                 'boosting_type':['gbdt','gbdt','gbdt','dart','gbdt','dart','gbdt','gbdt']
                },
          
         'MLPClassifier': { 'n_variables':[5,5,5,5,5,5,5,5,5],
                            'hidden_layer_sizes':[(100),(10),(50,50),(50,50),(100,100,100),(25,25,25),(1),(1),(1)],\
                            'activation':['relu','relu','relu','logistic','logistic','logistic','relu','relu','logistic'],
                            'solver':['adam','adam','adam','adam','sgd','sgd','adam','sgd','adam'], \
                            'alpha' : [0.0001,0.0001,0.001,0.0001,0.0001,0.0001,0.0001,0.0001,0.0001],\
                            'learning_rate':['constant','invscaling','adaptive','constant','constant','constant','constant','constant','constant'],\
                            'learning_rate_init':[0.001,0.001,0.001,0.025,0.5,0.05,0.001,0.001,0.001]},
          
          'KNeighborsClassifier':  { 'n_variables':[5],'n_neighbors':[5],'weights':['uniform']},
          
          'SVC' : { 'n_variables':[5,5], 'kernel':["rbf","linear"]}
         
         
         }

In [43]:
# with pd.ExcelWriter('test.xlsx') as writer:  
#         pd.DataFrame().to_excel(writer, sheet_name='test1')

# writer = pd.ExcelWriter('test.xlsx')
# pd.DataFrame().to_excel(writer, sheet_name='test2')
# pd.DataFrame().to_excel(writer, sheet_name='test1')
# writer.save()
# writer.close()

### Logistic Regression

In [44]:
if 'LogisticRegression' in modelsToRun:
    outputLR = modelAndOutput(modelName = 'LogisticRegression',criterionDict = hpDict['LogisticRegression'],\
                   X = X, Y_save = Y_save, filterCols = x3, nitermax = nitermax)
    outputDfList.append(outputLR)

train-test-split
model object created
training started
training ended
0 0.5133848899464605 0.5222098833981121 0.49832355406538137
train-test-split
model object created
training started
training ended
1 0.5149886540069271 0.5071546505228398 0.4941324392288349
train-test-split
model object created
training started
training ended
2 0.5165343131444826 0.515126050420168 0.49706621961441744
Scenario 0
trn    0.514969
tst    0.514830
oot    0.496507
dtype: float64
*************************Scenario 0 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5316037735849056 0.540119081372271 0.5146689019279128
train-test-split
model object created
training started
training ended
1 0.5351293615001187 0.5325328120636693 0.5155071248952221
train-test-split
model object created
training started
training ended
2 0.5322446060317082 0.5367606412382532 0.5150880134115675
Scenario 1
trn    0.532993
tst    0.536471
oot    0.515088
dtype: float64
*************************Scenario 1 completed***********************************************
train-test-split
model object created
training started

C:\Users\amrit\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

training ended
0 0.5297142173861055 0.5414379802414928 0.5171835708298408
train-test-split
model object created
training started

C:\Users\amrit\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

training ended
1 0.534930375265518 0.5290121709595245 0.5171835708298408
train-test-split
model object created
training started

C:\Users\amrit\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

training ended
2 0.5313963260895666 0.5377922784121806 0.5171835708298408
Scenario 2
trn    0.532014
tst    0.536081
oot    0.517184
dtype: float64
*************************Scenario 2 completed***********************************************
train-test-split
model object created
training started

C:\Users\amrit\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

training ended
0 0.5439140811455847 0.5448028673835126 0.5238893545683152
train-test-split
model object created
training started

C:\Users\amrit\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

training ended
1 0.5437425506555423 0.5468620403649433 0.5238893545683152
train-test-split
model object created
training started

C:\Users\amrit\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

training ended
2 0.5393575714789975 0.5547320410490307 0.5243084660519698
Scenario 3
trn    0.542338
tst    0.548799
oot    0.524029
dtype: float64
*************************Scenario 3 completed***********************************************
train-test-split
model object created
training started

C:\Users\amrit\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

training ended
0 0.5421122191517481 0.5483170466883822 0.5243084660519698
train-test-split
model object created
training started

C:\Users\amrit\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

training ended
1 0.5448871819491119 0.5425850340136055 0.5243084660519698
train-test-split
model object created
training started

C:\Users\amrit\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

training ended
2 0.5492857142857143 0.5558635985583588 0.5272422464375524
Scenario 4
trn    0.545428
tst    0.548922
oot    0.525286
dtype: float64
*************************Scenario 4 completed***********************************************

In [44]:
# outputLR = modelAndOutput(modelName = 'LogisticRegression',criterionDict = {'n_variables':[5]},\
#                X = X, Y_save = Y_save, filterCols = filterCols, nitermax = nitermax)

### Decision Tree

In [45]:
X.filter(x3)

,fulladdress_count_30,ssn_count_30,homephone_count_3,fulladdress_unique_count_for_dob_homephone_60,fulladdress_unique_count_for_ssn_30,fulladdress_unique_count_for_name_dob_30,ssn_dob_count_30,fulladdress_unique_count_for_dob_homephone_30,ssn_name_count_0_by_30,fulladdress_unique_count_for_ssn_zip5_30,...,fulladdress_unique_count_for_ssn_fulladdress_60,ssn_dob_count_0_by_30,ssn_name_dob_count_7,ssn_lastname_count_7,fulladdress_unique_count_for_name_dob_60,ssn_lastname_count_0_by_30,ssn_lastname_count_30,fulladdress_unique_count_for_fulladdress_dob_30,fulladdress_unique_count_for_name_fulladdress_60,ssn_count_0_by_14
0,-0.101958,-0.099006,-0.521454,-0.071988,-0.059602,-0.063475,-0.092879,-0.064481,0.171126,-0.059602,...,-0.062832,0.162987,-0.055635,-0.057154,-0.070165,0.171458,-0.097983,-0.063275,-0.061933,0.124777
1,-0.101958,-0.099006,-0.521454,-0.071988,-0.059602,-0.063475,-0.092879,-0.064481,0.171126,-0.059602,...,-0.062832,0.162987,-0.055635,-0.057154,-0.070165,0.171458,-0.097983,-0.063275,-0.061933,0.124777
2,-0.101958,-0.099006,-0.521454,-0.071988,-0.059602,-0.063475,-0.092879,-0.064481,0.171126,-0.059602,...,-0.062832,0.162987,-0.055635,-0.057154,-0.070165,0.171458,-0.097983,-0.063275,-0.061933,0.124777
3,-0.101958,-0.099006,-0.521454,-0.071988,-0.059602,-0.063475,-0.092879,-0.064481,0.171126,-0.059602,...,-0.062832,0.162987,-0.055635,-0.057154,-0.070165,0.171458,-0.097983,-0.063275,-0.061933,0.124777
4,-0.101958,-0.099006,-0.521454,-0.071988,-0.059602,-0.063475,-0.092879,-0.064481,0.171126,-0.059602,...,-0.062832,0.162987,-0.055635,-0.057154,-0.070165,0.171458,-0.097983,-0.063275,-0.061933,0.124777
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,-0.101958,-0.099006,-0.521454,-0.071988,-0.059602,-0.063475,-0.092879,-0.064481,0.171126,-0.059602,...,-0.062832,0.162987,-0.055635,-0.057154,-0.070165,0.171458,-0.097983,-0.063275,-0.061933,0.124777
999996,-0.101958,-0.099006,0.639148,-0.071988,-0.059602,-0.063475,-0.092879,-0.064481,0.171126,-0.059602,...,-0.062832,0.162987,-0.055635,-0.057154,-0.070165,0.171458,-0.097983,-0.063275,-0.061933,0.124777
999997,-0.101958,-0.099006,0.639148,-0.071988,-0.059602,-0.063475,-0.092879,-0.064481,0.171126,-0.059602,...,-0.062832,0.162987,-0.055635,-0.057154,-0.070165,0.171458,-0.097983,-0.063275,-0.061933,0.124777
999998,-0.101958,-0.099006,0.639148,-0.071988,-0.059602,-0.063475,-0.092879,-0.064481,0.171126,-0.059602,...,-0.062832,0.162987,-0.055635,-0.057154,-0.070165,0.171458,-0.097983,-0.063275,-0.061933,0.124777
999999,-0.101958,-0.099006,-0.521454,-0.071988,-0.059602,-0.063475,-0.092879,-0.064481,0.171126,-0.059602,...,-0.062832,0.162987,-0.055635,-0.057154,-0.070165,0.171458,-0.097983,-0.063275,-0.061933,0.124777

In [46]:
if 'DecisionTreeClassifier' in modelsToRun:
    outputDT = modelAndOutput(modelName = 'DecisionTreeClassifier',criterionDict = hpDict['DecisionTreeClassifier']
               , X = X, Y_save = Y_save, filterCols = x3, nitermax = nitermax)
    outputDfList.append(outputDT)

train-test-split
model object created
training started
training ended
0 0.5628110926759896 0.544410198935276 0.5322715842414082
train-test-split
model object created
training started
training ended
1 0.5589930596400423 0.5547632629777525 0.5352053646269908
train-test-split
model object created
training started
training ended
2 0.5661834600760456 0.5352269562795878 0.5318524727577536
Scenario 0
trn    0.562663
tst    0.544800
oot    0.533110
dtype: float64
*************************Scenario 0 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5579495678939268 0.5589887640449438 0.5335289186923722
train-test-split
model object created
training started
training ended
1 0.5593906212806474 0.5575589459084604 0.5331098072087175
train-test-split
model object created
training started
training ended
2 0.5593079748785401 0.5568946188340808 0.5335289186923722
Scenario 1
trn    0.558883
tst    0.557814
oot    0.533389
dtype: float64
*************************Scenario 1 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5631560325510083 0.5459183673469388 0.5322715842414082
train-test-split
model object created
training started
training ended
1 0.5604606525911708 0.5540724598202125 0.5331098072087175
train-test-split
model object created
training started
training ended
2 0.5633384779769678 0.5460379464285714 0.5297569153394803
Scenario 2
trn    0.562318
tst    0.548676
oot    0.531713
dtype: float64
*************************Scenario 2 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5278138655958426 0.5166666666666667 0.5020955574182733
train-test-split
model object created
training started
training ended
1 0.5213970675885088 0.5323383084577115 0.5020955574182733
train-test-split
model object created
training started
training ended
2 0.5219892150988616 0.531403604587657 0.5020955574182733
Scenario 3
trn    0.523733
tst    0.526803
oot    0.502096
dtype: float64
*************************Scenario 3 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.561353347629259 0.5516191530584003 0.5314333612740989
train-test-split
model object created
training started
training ended
1 0.5646161182641869 0.5451782260292899 0.5322715842414082
train-test-split
model object created
training started
training ended
2 0.5567354730939029 0.5650854936569222 0.5343671416596815
Scenario 4
trn    0.560902
tst    0.553961
oot    0.532691
dtype: float64
*************************Scenario 4 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.4809214412285883 0.4785431959345003 0.46563285834031853
train-test-split
model object created
training started
training ended
1 0.48161896778828883 0.474835886214442 0.4664710813076278
train-test-split
model object created
training started
training ended
2 0.4848736504923479 0.46198993851313586 0.4660519698239732
Scenario 5
trn    0.482471
tst    0.471790
oot    0.466052
dtype: float64
*************************Scenario 5 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.55072988297744 0.5734265734265734 0.5368818105616094
train-test-split
model object created
training started
training ended
1 0.5584492805327625 0.5578098943857699 0.5360435875943
train-test-split
model object created
training started
training ended
2 0.558398483771618 0.5584852734922862 0.5356244761106455
Scenario 6
trn    0.555859
tst    0.563241
oot    0.536183
dtype: float64
*************************Scenario 6 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5579466217840827 0.558959067497967 0.5305951383067896
train-test-split
model object created
training started
training ended
1 0.5593865176554512 0.5581201334816462 0.5293378038558256
train-test-split
model object created
training started
training ended
2 0.5658455708195168 0.5402750491159135 0.5268231349538978
Scenario 7
trn    0.561060
tst    0.552451
oot    0.528919
dtype: float64
*************************Scenario 7 completed***********************************************

In [47]:
# with pd.ExcelWriter('Assignment_8_output.xlsx') as writer:  
#     resultDf.to_excel(writer, sheet_name='Decision Tree')
#     worksheet = writer.sheets['Decision Tree']
# #     worksheet.conditional_format('F2:F8', {'type': 'number'})
#     workbook  = writer.book
#     format1 = workbook.add_format({'num_format': '0.00'})
#     worksheet.set_column('F:H', None, format1)
#     writer.save()

### Random forest

In [48]:
if 'RandomForestClassifier' in modelsToRun:
    outputRF = modelAndOutput(modelName = 'RandomForestClassifier',criterionDict = hpDict['RandomForestClassifier']
               , X = X, Y_save = Y_save, filterCols = x3, nitermax = nitermax)
    outputDfList.append(outputRF)

train-test-split
model object created
training started
training ended
0 0.5556349773647844 0.5649045114862995 0.537300922045264
train-test-split
model object created
training started
training ended
1 0.5593301435406699 0.5552508911434055 0.5360435875943
train-test-split
model object created
training started
training ended
2 0.5553039332538736 0.5656621509538291 0.5364626990779547
Scenario 0
trn    0.556756
tst    0.561939
oot    0.536602
dtype: float64
*************************Scenario 0 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5527590688881011 0.5778781038374717 0.5360435875943
train-test-split
model object created
training started
training ended
1 0.5657769304099142 0.54716459197787 0.5352053646269908
train-test-split
model object created
training started
training ended
2 0.5559661461437597 0.5702045328911001 0.5364626990779547
Scenario 1
trn    0.558167
tst    0.565082
oot    0.535904
dtype: float64
*************************Scenario 1 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5657547396208303 0.5453307922679009 0.5364626990779547
train-test-split
model object created
training started
training ended
1 0.5595879746077375 0.562055768179333 0.5360435875943
train-test-split
model object created
training started
training ended
2 0.5616682509505704 0.5541631857421331 0.5381391450125733
Scenario 2
trn    0.562337
tst    0.553850
oot    0.536882
dtype: float64
*************************Scenario 2 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5570180686849348 0.5676712328767123 0.5356244761106455
train-test-split
model object created
training started
training ended
1 0.554482271174461 0.5744741330301307 0.5360435875943
train-test-split
model object created
training started
training ended
2 0.5606186793575253 0.55941143808995 0.5352053646269908
Scenario 3
trn    0.557373
tst    0.567186
oot    0.535624
dtype: float64
*************************Scenario 3 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.555993785108163 0.570054945054945 0.5360435875943
train-test-split
model object created
training started
training ended
1 0.5524232245681382 0.5769545083083628 0.5360435875943
train-test-split
model object created
training started
training ended
2 0.5599856321839081 0.559781121751026 0.5356244761106455
Scenario 4
trn    0.556134
tst    0.568930
oot    0.535904
dtype: float64
*************************Scenario 4 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5631786183033051 0.5554329840044125 0.5360435875943
train-test-split
model object created
training started
training ended
1 0.5620429346543996 0.5559648625672995 0.5364626990779547
train-test-split
model object created
training started
training ended
2 0.5620247148288974 0.556947925368978 0.5364626990779547
Scenario 5
trn    0.562415
tst    0.556115
oot    0.536323
dtype: float64
*************************Scenario 5 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5568520061912132 0.5546008869179601 0.5368818105616094
train-test-split
model object created
training started
training ended
1 0.5584847405296283 0.5504740658114892 0.5364626990779547
train-test-split
model object created
training started
training ended
2 0.5564391691394659 0.5541596873255165 0.5352053646269908
Scenario 6
trn    0.557259
tst    0.553078
oot    0.536183
dtype: float64
*************************Scenario 6 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5600571973307912 0.5612724757952974 0.5364626990779547
train-test-split
model object created
training started
training ended
1 0.558663190329462 0.5645839170636032 0.5377200335289187
train-test-split
model object created
training started
training ended
2 0.5649265320750209 0.5506050605060506 0.5368818105616094
Scenario 7
trn    0.561216
tst    0.558820
oot    0.537022
dtype: float64
*************************Scenario 7 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5605771523968519 0.5523336095001381 0.5364626990779547
train-test-split
model object created
training started
training ended
1 0.5536952882085625 0.5692729766803841 0.5360435875943
train-test-split
model object created
training started
training ended
2 0.5560730920816912 0.5632911392405063 0.5368818105616094
Scenario 8
trn    0.556782
tst    0.561633
oot    0.536463
dtype: float64
*************************Scenario 8 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.54189012036706 0.5500553097345132 0.5217937971500419
train-test-split
model object created
training started
training ended
1 0.5456287425149701 0.5425211922340717 0.5230511316010059
train-test-split
model object created
training started
training ended
2 0.5412898619704902 0.5487094088259784 0.5217937971500419
Scenario 9
trn    0.542936
tst    0.547095
oot    0.522213
dtype: float64
*************************Scenario 9 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.552228248054704 0.5713475177304964 0.5381391450125733
train-test-split
model object created
training started
training ended
1 0.559367999056715 0.5553034600113443 0.5360435875943
train-test-split
model object created
training started
training ended
2 0.5580255766702522 0.5604395604395604 0.5347862531433362
Scenario 10
trn    0.556541
tst    0.562364
oot    0.536323
dtype: float64
*************************Scenario 10 completed***********************************************

In [49]:
# outputRF2 = modelAndOutput(modelName = 'RandomForestClassifier',criterionDict = {'n_variables':[5,15,15,15,15,30,5,30],'criterion':['gini','gini','entropy','gini','entropy','entropy','gini','gini'],\
#                'max_depth': [None,None,None,4,1000,2,None,10000],'min_samples_split':[2,2,2,2,2,2,100,2], 'max_features':[5,15,15,15,15,10,5,30],'min_samples_leaf':[1,1,1,1,1,1,50,1] }
#                , X = X, Y_save = Y_save, filterCols = filterCols, nitermax = nitermax)

### LGB

In [50]:
if 'lgb' in modelsToRun:
    outputLGB = modelAndOutput(modelName = 'lgb',criterionDict = hpDict['lgb'], X = X, Y_save = Y_save, filterCols = x3, nitermax = nitermax)
    outputDfList.append(outputLGB)

train-test-split
model object created
training started
training ended
0 0.5594095055208833 0.5572789115646258 0.5381391450125733
train-test-split
model object created
training started
training ended
1 0.5605338417540515 0.5518672199170125 0.5377200335289187
train-test-split
model object created
training started
training ended
2 0.5564035296923444 0.5617232808616405 0.5368818105616094
Scenario 0
trn    0.558782
tst    0.556956
oot    0.537580
dtype: float64
*************************Scenario 0 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.561317949327941 0.5572222222222222 0.5368818105616094
train-test-split
model object created
training started
training ended
1 0.561043018505167 0.5582089552238806 0.5377200335289187
train-test-split
model object created
training started
training ended
2 0.5641333013665788 0.5503410641200546 0.537300922045264
Scenario 1
trn    0.562165
tst    0.555257
oot    0.537301
dtype: float64
*************************Scenario 1 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5600664767331434 0.5593078425900083 0.5360435875943
train-test-split
model object created
training started
training ended
1 0.5626561942163513 0.5521642619311876 0.537300922045264
train-test-split
model object created
training started
training ended
2 0.5597967383597259 0.5568406205923836 0.5356244761106455
Scenario 2
trn    0.560840
tst    0.556104
oot    0.536323
dtype: float64
*************************Scenario 2 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5601620204908268 0.5588153888735123 0.5381391450125733
train-test-split
model object created
training started
training ended
1 0.5565686862627475 0.5669934640522876 0.5360435875943
train-test-split
model object created
training started
training ended
2 0.5578797242690754 0.5630392429724465 0.5364626990779547
Scenario 3
trn    0.558203
tst    0.562949
oot    0.536882
dtype: float64
*************************Scenario 3 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5609200910506769 0.559016393442623 0.5377200335289187
train-test-split
model object created
training started
training ended
1 0.5595663569216107 0.5618599501799059 0.5364626990779547
train-test-split
model object created
training started
training ended
2 0.562559694364852 0.5538419168273203 0.5356244761106455
Scenario 4
trn    0.561015
tst    0.558239
oot    0.536602
dtype: float64
*************************Scenario 4 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5611330225887415 0.5530219780219781 0.5356244761106455
train-test-split
model object created
training started
training ended
1 0.5634108153679392 0.5461663066954644 0.5364626990779547
train-test-split
model object created
training started
training ended
2 0.5569363125821484 0.5634964266080263 0.5368818105616094
Scenario 5
trn    0.560493
tst    0.554228
oot    0.536323
dtype: float64
*************************Scenario 5 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5288931252234005 0.5351411178749308 0.5046102263202011
train-test-split
model object created
training started
training ended
1 0.5311073744895508 0.5294756859549036 0.5046102263202011
train-test-split
model object created
training started
training ended
2 0.526397146254459 0.5385043091465109 0.5054484492875104
Scenario 6
trn    0.528799
tst    0.534374
oot    0.504890
dtype: float64
*************************Scenario 6 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5585208233604595 0.5565598466173651 0.5356244761106455
train-test-split
model object created
training started
training ended
1 0.5576555023923445 0.5607348505621058 0.5377200335289187
train-test-split
model object created
training started
training ended
2 0.5571073499822464 0.56070826306914 0.5381391450125733
Scenario 7
trn    0.557761
tst    0.559334
oot    0.537161
dtype: float64
*************************Scenario 7 completed***********************************************

### Neural Network

In [51]:
if 'MLPClassifier' in modelsToRun:
    outputNN = modelAndOutput(modelName = 'MLPClassifier',criterionDict = hpDict['MLPClassifier'] ,\
                                                            X = X, Y_save = Y_save, filterCols = x3, nitermax = 3)
    outputDfList.append(outputNN)

train-test-split
model object created
training started
training ended
0 0.5558840922531046 0.5627815315315315 0.5368818105616094
train-test-split
model object created
training started
training ended
1 0.5582713425433935 0.5576596947427925 0.537300922045264
train-test-split
model object created
training started
training ended
2 0.5611322549952427 0.5518199499861073 0.5368818105616094
Scenario 0
trn    0.558429
tst    0.557420
oot    0.537022
dtype: float64
*************************Scenario 0 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.559688995215311 0.5530573073759254 0.5356244761106455
train-test-split
model object created
training started
training ended
1 0.5570469798657718 0.5599235599235599 0.5364626990779547
train-test-split
model object created
training started
training ended
2 0.5352486721390632 0.5369325812516788 0.510896898575021
Scenario 1
trn    0.550662
tst    0.549971
oot    0.527661
dtype: float64
*************************Scenario 1 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5634911172051985 0.5469613259668509 0.537300922045264
train-test-split
model object created
training started
training ended
1 0.5594828608705966 0.555089485458613 0.5381391450125733
train-test-split
model object created
training started
training ended
2 0.5597220558284414 0.5551912568306011 0.538558256496228
Scenario 2
trn    0.560899
tst    0.552414
oot    0.537999
dtype: float64
*************************Scenario 2 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.56126953824126 0.5507446221731936 0.5368818105616094
train-test-split
model object created
training started
training ended
1 0.5603356577236733 0.5524534686971235 0.5368818105616094
train-test-split
model object created
training started
training ended
2 0.5565723793677204 0.5596994155301976 0.5381391450125733
Scenario 3
trn    0.559393
tst    0.554299
oot    0.537301
dtype: float64
*************************Scenario 3 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5587058823529412 0.5568862275449101 0.537300922045264
train-test-split
model object created
training started
training ended
1 0.555765595463138 0.563082133784928 0.5364626990779547
train-test-split
model object created
training started
training ended
2 0.5560018903591682 0.5625176404177251 0.5402347024308466
Scenario 4
trn    0.556824
tst    0.560829
oot    0.537999
dtype: float64
*************************Scenario 4 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5425848719475879 0.5434662236987818 0.5209555741827326
train-test-split
model object created
training started
training ended
1 0.5415094339622641 0.5636518287496456 0.5268231349538978
train-test-split
model object created
training started
training ended
2 0.544913741820345 0.5571904497501388 0.5264040234702431
Scenario 5
trn    0.543003
tst    0.554770
oot    0.524728
dtype: float64
*************************Scenario 5 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5489473058165815 0.5363888888888889 0.5188600167644594
train-test-split
model object created
training started
training ended
1 0.41327138432213484 0.4406310545253252 0.4195305951383068
train-test-split
model object created
training started
training ended
2 0.5180464562239429 0.5138427464008859 0.4974853310980721
Scenario 6
trn    0.493422
tst    0.496954
oot    0.478625
dtype: float64
*************************Scenario 6 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5136135657989014 0.5031654280209193 0.4941324392288349
train-test-split
model object created
training started
training ended
1 0.06102338834144604 0.06138392857142857 0.07334450963956413
train-test-split
model object created
training started
training ended
2 0.060783377119656076 0.06248279658684283 0.07418273260687343
Scenario 7
trn    0.211807
tst    0.209011
oot    0.213887
dtype: float64
*************************Scenario 7 completed***********************************************
train-test-split
model object created
training started
training ended
0 0.5463806327900288 0.5348075348075348 0.5205364626990779
train-test-split
model object created
training started
training ended
1 0.5420461265523359 0.5442004504504504 0.5213746856663872
train-test-split
model object created
training started
training ended
2 0.5422401518747034 0.5431684828164292 0.5213746856663872
Scenario 8
trn    0.543556
tst    0.540725
oot    0.521095
dtype: float64
*************************Scenario 8 completed***********************************************

In [52]:
# outputNN = modelAndOutput(modelName = 'MLPClassifier',criterionDict = { 'n_variables':[5],
#                                                             'hidden_layer_sizes':[(1)],\
#                                                             'activation':["logistic"],
#                                                             'solver':['adam'], \
#                                                             'alpha' : [0.0001],\
#                                                             'learning_rate':['constant'],\
#                                                             'learning_rate_init':[0.001]},\
#                                                             X = X, Y_save = Y_save, filterCols = filterCols, nitermax = 3)

In [53]:
# outputNN2 = modelAndOutput(modelName = 'MLPClassifier',criterionDict = { 'n_variables':[5]*6,
#                                                             'hidden_layer_sizes':[(100),(10),(50,50),(50,50),(100,100,100),(25,25,25)],\
#                                                             'activation':["relu","relu","relu","logistic","logistic","logistic"],
#                                                             'solver':['adam','adam','adam','adam','sgd','sgd'], \
#                                                             'alpha' : [0.0001,0.0001,0.001,0.0001,0.0001,0.0001],\
#                                                             'learning_rate':['constant','invscaling','adaptive','constant','constant','constant'],\
#                                                             'learning_rate_init':[0.001,0.001,0.001,0.025,0.5,0.05]},\
#                                                             X = X, Y_save = Y_save, filterCols = filterCols, nitermax = 2)

### KNN

In [54]:
if 'KNeighborsClassifier' in modelsToRun:
    outputKNN = modelAndOutput(modelName = 'KNeighborsClassifier',criterionDict = hpDict['KNeighborsClassifier'],
                                X = X, Y_save = Y_save, filterCols = filterCols, nitermax = 2) #change nitermax
    outputDfList.append(outputKNN)

### SVM

In [55]:
if 'SVC' in modelsToRun:
    outputSVN = modelAndOutput(modelName = 'SVC',criterionDict = hpDict['SVC'],
                                                            X = X, Y_save = Y_save, filterCols = filterCols, nitermax = 1)
    outputDfList.append(outputSVN)

In [56]:
# print('duration: ', datetime.now() - start_time)

In [57]:
# writer2 = pd.ExcelWriter("test.xlsx")
# # for i in range(0,3):
# pd.DataFrame({'a':[1,2,3]}).to_excel(writer2, sheet_name = str(2))
# writer.save()
# writer.close()


# writer = pd.ExcelWriter("Assignment_8_output.xlsx")
# writer2 = pd.ExcelWriter('test.xlsx') #if_sheet_exists = 'overlay'
# for i in range(0,3):
#     pd.DataFrame().to_excel(writer2, sheet_name=f'test{i}')
# # pd.DataFrame().to_excel(writer2, sheet_name='test1')
# writer2.save()
# writer2.close()

In [58]:
# [outputDfList[i]['model'][0] for i in range(0,len(outputDfList))]

In [59]:
indexModel = [outputDfList[i]['model'][0] for i in range(0,len(outputDfList))]
finalDf = pd.concat(outputDfList, keys = indexModel).drop('model',axis = 1)

In [60]:
new_cols = [col for col in finalDf.columns if not col in ['trn','tst','oot','Best OOT']] + ['trn','tst','oot','Best OOT']
finalDf = finalDf[new_cols]

In [61]:
# finalDf.to_excel("test.xlsx")

In [62]:
num_format_cols = [list(finalDf.columns).index(i) for i in finalDf.columns if i in ['trn', 'tst', 'oot'] ]

In [63]:
list(finalDf.columns).index('Best OOT')

17

In [64]:
finalDf.columns

Index(['n_variables', 'criterion', 'max_depth', 'min_samples_split',
       'max_features', 'min_samples_leaf', 'num_leaves', 'learning_rate',
       'boosting_type', 'hidden_layer_sizes', 'activation', 'solver', 'alpha',
       'learning_rate_init', 'trn', 'tst', 'oot', 'Best OOT'],
      dtype='object')

In [65]:
with pd.ExcelWriter('Model_Performances.xlsx') as writer:  
    finalDf.to_excel(writer, sheet_name='Results')
    worksheet = writer.sheets['Results']
#     worksheet.conditional_format('F2:F8', {'type': 'number'})
    workbook  = writer.book
    format1 = workbook.add_format({'num_format': '0.000'})
    bold = workbook.add_format({'bold': True})
    for i in num_format_cols:
        worksheet.set_column(i+2,i+2, None, format1) 
    writer.save()

C:\Users\amrit\anaconda3\lib\site-packages\xlsxwriter\workbook.py:336: UserWarning: Calling close() on already closed file.
  warn("Calling close() on already closed file.")

In [66]:
assert 1==2

AssertionError:

In [68]:
#best model


criterionDict = {'n_variables':[5],
                'num_leaves':[31],
                'learning_rate':[0.1],
                'boosting_type':['gbdt']}
modelName = 'lgb'
i = 0
X_trntst = X[0:833507]
Y_trntst = Y_save[0:833507]
X_oot = X[833507:]
Y_oot = Y_save[833507:]
n = criterionDict['n_variables'][i]
X_trntst = X_trntst.filter(filterCols[0:n])
X_oot = X_oot.filter(filterCols[0:n])
X_oot_orig = X_oot.copy()

FDR3 = pd.DataFrame(np.zeros((nitermax,3)), columns=('trn', 'tst', 'oot'))
nitermax = 1

for niter in range(nitermax):  
    print("train-test-split")
    X_trn, X_tst, Y_trn, Y_tst = train_test_split(X_trntst, Y_trntst, test_size = .3)


    if modelName == 'DecisionTreeClassifier':
        model = DecisionTreeClassifier(criterion = criterionDict['criterion'][i], max_depth = criterionDict['max_depth'][i],
                                  max_features = criterionDict['max_features'][i], min_samples_split = criterionDict['min_samples_split'][i],\
                                          min_samples_leaf = criterionDict['min_samples_leaf'][i])



    elif modelName == 'RandomForestClassifier':
        model = RandomForestClassifier(criterion = criterionDict['criterion'][i], max_depth = criterionDict['max_depth'][i],
                                  max_features = criterionDict['max_features'][i],min_samples_split = criterionDict['min_samples_split'][i],\
                                          min_samples_leaf = criterionDict['min_samples_leaf'][i])


    elif modelName == 'lgb':
        model = lgb.LGBMClassifier(learning_rate = criterionDict['learning_rate'][i],\
                                       boosting_type = criterionDict['boosting_type'][i],\
                                       num_leaves = criterionDict['num_leaves'][i])

    elif modelName == 'LogisticRegression':
        if len([i for i in criterionDict.keys() if i!='n_variables'])!=0:
            raise Exception("Hyperparameter tuning not implemented for Logistic Regression")
        model = LogisticRegression()

    elif modelName == 'MLPClassifier':
        model = MLPClassifier(hidden_layer_sizes = criterionDict['hidden_layer_sizes'][i],
                                  activation = criterionDict['activation'][i],
                                  solver = criterionDict['solver'][i],
                                  alpha = criterionDict['alpha'][i],
                                  learning_rate = criterionDict['learning_rate'][i],
                                  learning_rate_init = criterionDict['learning_rate_init'][i])

    elif modelName == 'SVC':
        model = SVC(kernel = criterionDict['kernel'][i],probability = True)

    elif modelName == 'KNeighborsClassifier':
        model = KNeighborsClassifier(n_neighbors = criterionDict['n_neighbors'][i],weights = criterionDict['weights'][i])

    else:
        raise Exception("Not implemented yet")


    print("model object created")

    X_oot = X_oot_orig.copy()
    X_trn_save = X_trn.copy()
    Y_trn_save = Y_trn.copy()

    print("training started")
    model.fit(X_trn, Y_trn.values.ravel())   
    print("training ended")
    predictions = model.predict_proba(X_trn_save)[:,1]
    X_trn['predicted'] = predictions
    X_trn['fraud_label'] = Y_trn_save['fraud_label']
    topRows = int(round(X_trn.shape[0]*0.03))
    temp = X_trn.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'trn'] = sum(needed)/sum(X_trn.loc[:,'fraud_label'])

    predictions = model.predict_proba(X_tst)[:,1]
    X_tst['predicted']=predictions
    X_tst['fraud_label'] = Y_tst['fraud_label']
    topRows = int(round(X_tst.shape[0]*0.03))
    temp = X_tst.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'tst'] = sum(needed)/sum(X_tst.loc[:,'fraud_label'])

    predictions = model.predict_proba(X_oot)[:,1]
    X_oot['predicted']=predictions
    X_oot['fraud_label'] = Y_oot['fraud_label']
    topRows = int(round(X_oot.shape[0]*0.03))
    temp = X_oot.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'fraud_label']
    FDR3.loc[niter, 'oot'] = sum(needed)/sum(X_oot.loc[:,'fraud_label'])
    print(niter, FDR3.loc[niter, 'trn'],FDR3.loc[niter, 'tst'],FDR3.loc[niter, 'oot'])
print("Scenario "+ str(i))
print(FDR3.mean())
# FDR_results.append(FDR3.mean())
print(f"*************************Scenario {i} completed***********************************************")

train-test-split
model object created
training started
training ended
0 0.5575062701540666 0.5608145294441387 0.5377200335289187
Scenario 0
trn    0.185835
tst    0.186938
oot    0.179240
dtype: float64

NameError: name 'FDR_results' is not defined

,fulladdress_count_30,ssn_count_30,homephone_count_3,fulladdress_unique_count_for_dob_homephone_60,fulladdress_unique_count_for_ssn_30,predicted,fraud_label
574420,-0.101958,-0.099006,0.639148,-0.071988,-0.059602,0.006683,0
763834,-0.101958,-0.099006,-0.521454,-0.071988,-0.059602,0.006339,0
492673,-0.101958,-0.099006,-0.521454,-0.071988,-0.059602,0.006339,0
542509,-0.101958,-0.099006,-0.521454,-0.071988,-0.059602,0.006339,0
761422,-0.101958,-0.099006,-0.521454,-0.071988,-0.059602,0.006339,0
...,...,...,...,...,...,...,...
160862,-0.101958,-0.099006,-0.521454,-0.071988,-0.059602,0.006339,0
483610,-0.101958,-0.099006,-0.521454,-0.071988,-0.059602,0.006339,0
41280,-0.101958,-0.099006,-0.521454,-0.071988,-0.059602,0.006339,0
48783,-0.101958,-0.099006,0.639148,-0.071988,-0.059602,0.006683,0
568460,-0.101958,-0.099006,0.639148,-0.071988,-0.059602,0.006683,0

In [75]:
X_trn.shape[0]*0.01*0

0.0

In [90]:
#professor code
X_trn_eval = X_trn.filter(['fraud_label','predicted'])
X_tst_eval = X_tst.filter(['fraud_label','predicted'])
X_oot_eval = X_oot.filter(['fraud_label','predicted'])

cols = ['bin','#recs','#g','#b','%g','%b','tot','cg','cb','%cg','FDR','KS','FPR']
FDR_trn = pd.DataFrame(np.zeros((101, 13)), columns = cols)
FDR_tst = pd.DataFrame(np.zeros((101, 13)), columns = cols)
FDR_oot = pd.DataFrame(np.zeros((101, 13)), columns = cols)
trn_sorted = X_trn_eval.sort_values('predicted',ascending=False) # X_trn
tst_sorted = X_tst_eval.sort_values('predicted',ascending=False) # X_tst
oot_sorted = X_oot_eval.sort_values('predicted',ascending=False) # X_oot
bad_tot_trn = sum(X_trn_eval.loc[:, 'fraud_label'])
bad_tot_tst = sum(X_tst_eval.loc[:, 'fraud_label'])
bad_tot_oot = sum(X_oot_eval.loc[:, 'fraud_label'])
num_tot_trn = len(X_trn_eval)
num_tot_tst = len(X_tst_eval)
num_tot_oot = len(X_oot_eval)
good_tot_trn = num_tot_trn - bad_tot_trn
good_tot_tst = num_tot_tst - bad_tot_tst
good_tot_oot = num_tot_oot - bad_tot_oot

for i in range(101):
    percent_rows_trn = int(round(X_trn_eval.shape[0]*0.01*i))
    percent_rows_tst = int(round(X_tst_eval.shape[0]*0.01*i))
    percent_rows_oot = int(round(X_oot_eval.shape[0]*0.01*i))
    temp_trn = trn_sorted.head(percent_rows_trn)
    temp_tst = tst_sorted.head(percent_rows_tst)
    temp_oot = oot_sorted.head(percent_rows_oot)
    num_bad_trn = sum(temp_trn.loc[:,'fraud_label'])
    num_bad_tst = sum(temp_tst.loc[:,'fraud_label'])
    num_bad_oot = sum(temp_oot.loc[:,'fraud_label'])
    num_tot_trn = len(temp_trn)
    num_tot_tst = len(temp_tst)
    num_tot_oot = len(temp_oot)
    num_good_trn = num_tot_trn - num_bad_trn
    num_good_tst = num_tot_tst - num_bad_tst
    num_good_oot = num_tot_oot - num_bad_oot
    FDR_trn.loc[i, 'bin'] = i
    FDR_trn.loc[i,'#recs'] = 0
    FDR_trn.loc[i, 'tot'] = num_tot_trn
    FDR_trn.loc[i, 'cg'] = num_good_trn
    FDR_trn.loc[i, 'cb'] = num_bad_trn
    FDR_tst.loc[i, 'bin'] = i
    FDR_tst.loc[i, 'tot'] = num_tot_tst
    FDR_tst.loc[i, 'cg'] = num_good_tst
    FDR_tst.loc[i, 'cb'] = num_bad_tst
    FDR_oot.loc[i, 'bin'] = i
    FDR_oot.loc[i, 'tot'] = num_tot_oot
    FDR_oot.loc[i, 'cg'] = num_good_oot
    FDR_oot.loc[i, 'cb'] = num_bad_oot
    if i != 0:
        FDR_trn.loc[i, '#g'] = num_good_trn - FDR_trn.loc[i-1, 'cg']
        FDR_trn.loc[i, '#b'] = num_bad_trn - FDR_trn.loc[i-1, 'cb']
        FDR_trn.loc[i,'#recs'] = FDR_trn.loc[i, '#g'] + FDR_trn.loc[i, '#b']
        FDR_trn.loc[i, '%g'] = 100* (num_good_trn - FDR_trn.loc[i-1, 'cg']) / (num_tot_trn - FDR_trn.loc[i-1, 'tot'])
        FDR_trn.loc[i, '%b'] = 100 - FDR_trn.loc[i, '%g']
        FDR_trn.loc[i, '%cg'] = 100 * num_good_trn / good_tot_trn
        FDR_trn.loc[i, 'FDR'] = 100 * num_bad_trn / bad_tot_trn
        FDR_trn.loc[i, 'KS'] = FDR_trn.loc[i, 'FDR'] - FDR_trn.loc[i, '%cg']
        FDR_trn.loc[i, 'FPR'] = num_good_trn / num_bad_trn
        FDR_tst.loc[i, '#g'] = num_good_tst - FDR_tst.loc[i-1, 'cg']
        FDR_tst.loc[i, '#b'] = num_bad_tst - FDR_tst.loc[i-1, 'cb']
        FDR_tst.loc[i,'#recs'] = FDR_tst.loc[i, '#g'] + FDR_tst.loc[i, '#b']
        FDR_tst.loc[i, '%g'] = 100* (num_good_tst - FDR_tst.loc[i-1, 'cg']) / (num_tot_tst - FDR_tst.loc[i-1, 'tot'])
        FDR_tst.loc[i, '%b'] = 100 - FDR_tst.loc[i, '%g']
        FDR_tst.loc[i, '%cg'] = 100 * num_good_tst / good_tot_tst
        FDR_tst.loc[i, 'FDR'] = 100 * num_bad_tst / bad_tot_tst
        FDR_tst.loc[i, 'KS'] = FDR_tst.loc[i, 'FDR'] - FDR_tst.loc[i, '%cg']
        FDR_tst.loc[i, 'FPR'] = num_good_tst / num_bad_tst
        FDR_oot.loc[i, '#g'] = num_good_oot - FDR_oot.loc[i-1, 'cg']
        FDR_oot.loc[i, '#b'] = num_bad_oot - FDR_oot.loc[i-1, 'cb']
        FDR_oot.loc[i,'#recs'] = FDR_oot.loc[i, '#g'] + FDR_oot.loc[i, '#b']
        FDR_oot.loc[i, '%g'] = 100* (num_good_oot - FDR_oot.loc[i-1, 'cg']) / (num_tot_oot - FDR_oot.loc[i-1, 'tot'])
        FDR_oot.loc[i, '%b'] = 100 - FDR_oot.loc[i, '%g']
        FDR_oot.loc[i, '%cg'] = 100 * num_good_oot / good_tot_oot
        FDR_oot.loc[i, 'FDR'] = 100 * num_bad_oot / bad_tot_oot
        FDR_oot.loc[i, 'KS'] = FDR_oot.loc[i, 'FDR'] - FDR_oot.loc[i, '%cg']
        FDR_oot.loc[i, 'FPR'] = num_good_oot / num_bad_oot

In [91]:
FDR_trn.head(21)

,bin,#recs,#g,#b,%g,%b,tot,cg,cb,%cg,FDR,KS,FPR
0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000
1,1.0,5835.0,1551.0,4284.0,26.580977,73.419023,5835.0,1551.0,4284.0,0.269701,51.164457,50.894756,0.362045
2,2.0,5834.0,5523.0,311.0,94.669181,5.330819,11669.0,7074.0,4595.0,1.230088,54.878777,53.648689,1.539499
3,3.0,5835.0,5762.0,73.0,98.748929,1.251071,17504.0,12836.0,4668.0,2.232033,55.750627,53.518594,2.749786
4,4.0,5834.0,5769.0,65.0,98.885842,1.114158,23338.0,18605.0,4733.0,3.235196,56.526932,53.291735,3.930911
5,5.0,5835.0,5784.0,51.0,99.125964,0.874036,29173.0,24389.0,4784.0,4.240968,57.136032,52.895065,5.098035
6,6.0,5834.0,5789.0,45.0,99.228660,0.771340,35007.0,30178.0,4829.0,5.247609,57.673474,52.425866,6.249327
7,7.0,5835.0,5785.0,50.0,99.143102,0.856898,40842.0,35963.0,4879.0,6.253554,58.270632,52.017078,7.370978
8,8.0,5834.0,5793.0,41.0,99.297223,0.702777,46676.0,41756.0,4920.0,7.260890,58.760301,51.499411,8.486992
9,9.0,5835.0,5788.0,47.0,99.194516,0.805484,52511.0,47544.0,4967.0,8.267357,59.321629,51.054272,9.571975
10,10.0,5834.0,5790.0,44.0,99.245800,0.754200,58345.0,53334.0,5011.0,9.274172,59.847128,50.572956,10.643385
11,11.0,5835.0,5786.0,49.0,99.160240,0.839760,64180.0,59120.0,5060.0,10.280291,60.432342,50.152051,11.683794
12,12.0,5834.0,5793.0,41.0,99.297223,0.702777,70014.0,64913.0,5101.0,11.287627,60.922011,49.634384,12.725544
13,13.0,5835.0,5792.0,43.0,99.263068,0.736932,75849.0,70705.0,5144.0,12.294790,61.435567,49.140777,13.745140
14,14.0,5835.0,5805.0,30.0,99.485861,0.514139,81684.0,76510.0,5174.0,13.304213,61.793861,48.489648,14.787399
15,15.0,5834.0,5800.0,34.0,99.417209,0.582791,87518.0,82310.0,5208.0,14.312766,62.199928,47.887162,15.804531
16,16.0,5835.0,5791.0,44.0,99.245930,0.754070,93353.0,88101.0,5252.0,15.319755,62.725427,47.405672,16.774752
17,17.0,5834.0,5789.0,45.0,99.228660,0.771340,99187.0,93890.0,5297.0,16.326396,63.262869,46.936473,17.725127
18,18.0,5835.0,5793.0,42.0,99.280206,0.719794,105022.0,99683.0,5339.0,17.333732,63.764481,46.430749,18.670725
19,19.0,5834.0,5798.0,36.0,99.382928,0.617072,110856.0,105481.0,5375.0,18.341938,64.194434,45.852497,19.624372
20,20.0,5835.0,5802.0,33.0,99.434447,0.565553,116691.0,111283.0,5408.0,19.350839,64.588558,45.237719,20.577478

In [106]:
with pd.ExcelWriter('Results_rows.xlsx') as writer:  
        FDR_trn.to_excel(writer, sheet_name='train')
        FDR_tst.to_excel(writer, sheet_name='test')
        FDR_oot.to_excel(writer, sheet_name='oot')

In [92]:
5835.0*101

589335.0

In [94]:
len(X_trn)

583454

In [98]:
len(X_tst) + len(X_trn) + len(X_oot)

1000000

In [99]:
len(X_tst) + len(X_trn)

833507

In [104]:
0.8*833507

666805.6000000001

In [105]:
666805/100

6668.05

In [88]:
X_trn

0.006339    375824
0.006683    140385
0.008520     34804
0.005241      7397
0.015425      6473
             ...
0.088206         1
0.994173         1
0.995929         1
0.903173         1
0.059625         1
Name: predicted, Length: 326, dtype: int64

In [85]:
X_trn_eval = X_trn.filter(['record','fraud_label','predicted'])
X_tst_eval = X_tst.filter(['record','fraud_label','predicted'])
X_oot_eval = X_oot.filter(['record','fraud_label','predicted'])

X_trn_eval['bin'] = pd.cut(X_trn_eval['predicted'],101)
X_tst_eval['bin'] = pd.cut(X_trn_eval['predicted'],101)
X_oot_eval['bin'] = pd.cut(X_trn_eval['predicted'],101)

FDR_trn = X_trn_eval.groupby('bin').agg({'predicted':'count','fraud_label':np.sum}).rename(columns = {'predicted':'#Records','fraud_label':'#Bads'})
FDR_trn['%Bads'] = FDR_trn['#Bads']/FDR_trn['#Records']
FDR_trn['#Goods'] = FDR_trn['#Records'] - FDR_trn['#Bads']
FDR_trn['%Goods'] = FDR_trn['#Goods']/FDR_trn['#Records']

FDR_trn['Cumulative_Bads'] = np.cumsum(FDR_trn['#Bads'])
FDR_trn['Cumulative_Goods'] = np.cumsum(FDR_trn['#Goods'])
FDR_trn['Cumulative_%Goods'] = FDR_trn['Cumulative_Goods'] / len(X_trn_eval[X_trn_eval['fraud_label']==0])
FDR_trn['Cumulative_%Bads'] = FDR_trn['Cumulative_Bads'] / len(X_trn_eval[X_trn_eval['fraud_label']==1]) #check
FDR_trn['KS'] = FDR_trn['Cumulative_%Bads'] - FDR_trn['Cumulative_%Goods'] #Cumulative_%Bads = FDR
FDR_trn['FPR'] = FDR_trn['Cumulative_Goods'] / FDR_trn['Cumulative_Bads']

In [86]:
FDR_trn

,#Records,#Bads,%Bads,#Goods,%Goods,Cumulative_Bads,Cumulative_Goods,Cumulative_%Goods,Cumulative_%Bads,KS,FPR
bin,,,,,,,,,,,
"(-0.000897, 0.01]",567670,3719,0.006551,563951,0.993449,3719,563951,0.980646,0.444166,-0.536480,151.640495
"(0.01, 0.0199]",6978,106,0.015191,6872,0.984809,3825,570823,0.992596,0.456826,-0.535770,149.234771
"(0.0199, 0.0298]",22,0,0.000000,22,1.000000,3825,570845,0.992634,0.456826,-0.535809,149.240523
"(0.0298, 0.0397]",95,3,0.031579,92,0.968421,3828,570937,0.992794,0.457184,-0.535610,149.147597
"(0.0397, 0.0496]",1216,58,0.047697,1158,0.952303,3886,572095,0.994808,0.464111,-0.530697,147.219506
...,...,...,...,...,...,...,...,...,...,...,...
"(0.95, 0.96]",58,56,0.965517,2,0.034483,7284,575066,0.999974,0.869939,-0.130035,78.949204
"(0.96, 0.97]",340,327,0.961765,13,0.038235,7611,575079,0.999997,0.908993,-0.091003,75.558928
"(0.97, 0.98]",91,89,0.978022,2,0.021978,7700,575081,1.000000,0.919623,-0.080377,74.685844
"(0.98, 0.99]",25,25,1.000000,0,0.000000,7725,575081,1.000000,0.922608,-0.077392,74.444142
"(0.99, 1.0]",648,648,1.000000,0,0.000000,8373,575081,1.000000,1.000000,0.000000,68.682790

### Ignore

In [ ]:
index_name = 'record'

In [ ]:
dfSave = df.copy()

In [ ]:
df = df.set_index(index_name)

In [ ]:
y_name = 'fraud_label'
good_label = 0
bad_label = 1
balance = 0

In [ ]:
df = df[df.index <= 833508] # remove the last two months as the out-of-time data (OOT)
df = df[df.index >= 38512] # remove the first 2 weeks of records since their variables aren't well formed
df['RANDOM'] = np.random.ranf(len(df)) # add a random number variable to make sure it doesn't come up as important
goods = df[df[y_name] == good_label]
bads = df[df[y_name] == bad_label]

In [ ]:
import scipy.stats as sps

In [ ]:
num_filter = 100

In [ ]:

"""
Setting the index before
"""


"""
changing below slicing commands so that they use index
"""




num_goods = len(goods)
num_bads = len(bads)
num_vars = len(bads.columns)-2
if(balance != 0):
    if(i == 0):
        num_goods_desired = int(min(num_goods,num_bads*balance))
        goods = goods.sample(n=num_goods_desired,random_state=1)
        """
        Now we will have list of record numbers in goods_keep
        """
        goods_keep = list(goods.index)
        goods_keep.sort()

    if(i > 0):
        """
        commenting below line since index is already set
        """
#             goods.set_index(index_name, inplace=True)
        goods.sort_index(inplace=True)
        """
        Using loc instead of iloc
        """
        goods = goods.loc[goods_keep] # THERE'S SOMETHING WRONG HERE AND I CAN'T FIGURE IT OUT

df_sampled = pd.concat([goods,bads])

"""
commenting below because we had already set the index before
"""
#     df_sampled.set_index(index_name, inplace=True)
df_sampled.sort_index(inplace=True)


"""
Removed some redundant lines in both the if statements
"""

filter_score = pd.DataFrame(np.zeros((num_vars+1,2)))
filter_score.columns = ['variable','score']   
j = 0
for column in df_sampled:
    filter_score.loc[j,'variable'] = column
    filter_score.loc[j,'score'] = sps.ks_2samp(goods[column],bads[column])[0]
    j = j+1
    if j%100 == 0:
        print(j)

filter_score.sort_values(by=['score'], ascending=False, inplace=True)
vars_keep = list(filter_score['variable'][1:num_filter+1])
#     print(filter_score.head(num_filter))


if(i == 0): # if first time through need to initialize some stuff
    Y = pd.DataFrame(df_sampled[y_name], index=df_sampled.index)
    df_top = df_sampled.filter(vars_keep, axis=1)

# if(i > 0): # if more than one variable file we use this loop
#     data_new_top = df_sampled.filter(vars_keep, axis=1)
#     df_top = pd.concat([df_top,data_new_top], axis=1)

"""
Not that it matters a lot but I usually put the dataframes in a list and concatenate them after coming out of loop.
Someone at my previous organization said that it was more efficient but I did not check the efficiency benefit myself.
"""
#     filter_score = pd.concat([filter_score,new])
# filter_score_df_list.append(filter_score)



# filter_score = pd.concat(filter_score_df_list)

In [ ]:
filter_score.merge(pd.DataFrame({'variable':x}), on = 'variable')

In [ ]:
detect_rate = .03

In [ ]:
from mlxtend.feature_selection import SequentialFeatureSelector as SFS

In [ ]:
def fdr(classifier, x, y, cutoff=detect_rate):
# Calculates FDR score for the given classifier on dataset x and y with cutoff value
# get the probability list from the given classifier
    return fdr_prob(y, classifier.predict_proba(x), cutoff)
def fdr_prob(y, y_prob, cutoff=detect_rate):
    if len(y_prob.shape) != 1:    # sometimes the proba list can contain many columns, one for each category
        y_prob = y_prob[:, -1:]   # only the last one (fraud_label==1) is used here.
    num_fraud = len(y[y == 1])    # count the total nunber of frauds   
# sort the proba list from high to low while retain the true (not predicted) fraud label
    sorted_prob = np.asarray(sorted(zip(y_prob, y), key=lambda x: x[0], reverse=True))
    cutoff_bin = sorted_prob[0:int(len(y) * cutoff), 1:]  # 3% cutoff
# return the FDR score (#fraud_in_cutoff / #total_fraud)
    return len(cutoff_bin[cutoff_bin == 1]) / num_fraud

In [ ]:
num_wrapper = 30

In [ ]:
Y = dfSave['fraud_label'].values 
X = dfSave.drop(['record','fraud_label'],axis = 1)

In [ ]:
%%time
# If you're doing forward selection it's enough to stop at num_wrapper variables. 
# If you're doing backward selection you need to go through all the variables to get 
# a sorted list of num_wrapper variables.
nfeatures = len(X.columns)
clf = RandomForestClassifier(n_estimators=5, n_jobs=-1) # simple, fast nonlinear model for the wrapper
sfs = SFS(clf,k_features=num_wrapper,forward=True,verbose=2,scoring=fdr,cv=2,n_jobs=-1) # forward selection
# sfs = SFS(clf,k_features=1,forward=False,verbose=2,scoring=fdr,cv=2,n_jobs=-1) # backward selection
sfs.fit(X,Y)

In [ ]:
import matplotlib.pyplot as plt
from mlxtend.plotting import plot_sequential_feature_selection as plot_sfs
fig1 = plot_sfs(sfs.get_metric_dict(),kind='std_dev', figsize=(15, 6))
plt.xticks(np.arange(0, len(X.columns), step=5))
plt.ylim([0., .7])
plt.xlim(0,num_wrapper)
plt.title('Stepwise Selection')
plt.grid()
plt.savefig('FS_fdr.png')
plt.show()

In [ ]:
vars_FS = pd.DataFrame.from_dict(sfs.get_metric_dict()).T
vars_FS.head()
vars_FS['Previous Features'] = vars_FS.feature_names.shift().fillna('')
vars_FS['New Feature'] = vars_FS.apply(lambda x : list(set(x['feature_names']) - set(x['Previous Features']))[0], axis = 1) 
vars_final = [i for i in vars_FS['New Feature']]
vars_FS.to_csv('VarsFS2.csv', index=False)

In [ ]:
vars_FS.filter(['New Feature','avg_score']).merge(filter_score, right_on = 'variable',left_on = 'New Feature').to_csv("VarsFS2.csv")

In [ ]:
filter_score